## spring
spring:
  config:
    activate:
      on-profile:
        - local
  application:
    name: flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration/schema
    url: jdbc:mysql://localhost:3306/test
    schemas: test
    user: root
    password: yun1109114
