# default profile
spring:
  profiles:
    include:
      - httpclient
      - oauth
    active: development
    ## Security
  security:
    permit-url: /api-docs/**,/configuration/**,/webjars/**,/health
    filter-skip: /health,/configuration,/webjars
    oauth2:
      client:
        registration:
          google:
            client-id: 469809305775-ksbip6mp90st3ob5t2ddk50edth3j4md.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: we5O8JJCsiLuKFAEQkHi
            client-secret: wxhEiwc5mJ
            scope:
              - profile
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:822/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: yun1109114
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql=true:
server:
  port: 822
  tomcat:
    connection-timeout: 30000
    max-threads: 100
    min-spare-threads: 50
    accept-count: 50
    uri-encoding: UTF-8