# default profile
spring:
  profiles:
    include:
      - httpclient
      - oauth
    active: development
    ## Security
  security:
    permit-url: /api-docs/**,/configuration/**,/webjars/**,/health
    filter-skip: /health,/configuration,/webjars
    oauth2:
      client:
        registration:
          google:
            client-id: <client-id>
            client-secret: <serect-key>
            scope:
              - profile
              - email
          naver:
            client-id: <client-id>
            client-secret: <serect-key>
            scope:
              - profile
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:822/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql=true:
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 822
  tomcat:
    connection-timeout: 30000
    max-threads: 100
    min-spare-threads: 50
    accept-count: 50
    uri-encoding: UTF-8

## AWS Setting
aws:
  s3:
    key:
      access: <access token>
      secret: <secret access token>
    client:
      region: ap-northeast-2
    bucket:
      name: bucket_name
    image:
      url:
        prefix: cdn-prefix
    upload:
      path.directory: directory